exports.employeeData = [{
  "_id": "1",
  "firstName": "John",
  "lastName": "Smith",
  "address1": "123 Hackreactor Rd",
  "address2": "",
  "city": "New York",
  "state": "NY",
  "zipcode": 10002,
  "country": "United States",
  "phone": "123-456-7890",
  "email": "jsmith@gmail.com",
  "wage": 15.00,
  "startDate": "2021-02-13",
  "position": "Front Desk",
  "weekHours": 30,
  "isActive": true
},
{
  "_id": "2",
  "firstName": "Jim",
  "lastName": "Smoth",
  "address1": "124 Hackreactor Rd",
  "address2": "",
  "city": "New York",
  "state": "NY",
  "zipcode": 10002,
  "country": "United States",
  "phone": "123-456-7890",
  "email": "jsmith@gmail.com",
  "wage": 15.00,
  "startDate": "2021-02-13",
  "position": "Front Desk",
  "weekHours": 30,
  "isActive": true
},
]